# Generated by Django 4.1.3 on 2022-11-29 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_lastname', models.CharField(max_length=200)),
                ('c_phone', models.CharField(max_length=50)),
                ('c_nick_name', models.CharField(max_length=200)),
                ('c_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('drink', models.CharField(max_length=50)),
                ('product_bought', models.CharField(max_length=100)),
                ('product_used', models.CharField(max_length=100)),
                ('payment_way', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
