# Generated by Django 4.1.3 on 2022-12-05 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 23, 10, 5, 585197, tzinfo=datetime.timezone.utc), verbose_name='Date Registered'),
        ),
        migrations.AddField(
            model_name='service',
            name='bougth_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 23, 10, 5, 624175, tzinfo=datetime.timezone.utc), verbose_name='Bougth Date'),
        ),
    ]
