# Generated by Django 4.1.3 on 2022-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_reg_date_service_bougth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reg_date',
            field=models.DateTimeField(verbose_name='Date Registered'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bougth_date',
            field=models.DateTimeField(verbose_name='Bougth Date'),
        ),
    ]
