# Generated by Django 4.1.3 on 2023-03-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_reg_date_alter_service_bougth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
